### ISSUE TITLE
URL is not included in the domains of the application.

### ISSUE THREAD

**Issue by MercadoXL** [facebook/php-graph-sdk#1005]
Hi, I hope you can help me, I know that this mistake has been very silly but I can not see the solution.
I have my app set up and in "domain of the aplicaicon" (basic configuration of the facebook app) I have placed my sub domain where I have the directory of the example and the main domain.

even so when I try the example I have this error

Can not load the URL: The domain of this URL is not included in the domains of the application. In order to load this URL, add all the domains and subdomains of your application in the "Application domains" field in the application settings.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
