### ISSUE TITLE
Facebook login window is not opening in safari browser.

### ISSUE THREAD

**Issue by sanga555** [facebook/php-graph-sdk#1006]
I am visiting an site say www.example.com trying to connect on Facebook from the iPhone device on safari browser.
The safari browser is restricting to open the Facebook window.
Whereas it is working on chrome browser on all iPhone device.

Where i observed and noticed that its working for iPhone device 5C on safari.
Its not working for iPhone 6, 6 plus devices and above on safari browser.
As these devices are having iOs version greater than 7 so this might be the issue.

Is there solution for this why i am not able to connect Facebook  on safari iPhone devices 6 and 6 plus on www.example.com

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
