### ISSUE TITLE
Does we cannot use read_custom_friendlists permission?

### ISSUE THREAD

**Issue by Koshukey** [facebook/php-graph-sdk#1007]
I try to get user's frined list through graph API.

When I read here(https://developers.facebook.com/docs/graph-api/reference/friend-list/),
it says that I need to get  read_custom_friendlists permission for getting friendlist.

However, when I try to get that permission, I met this error.

[![https://gyazo.com/1c975a7ff55cb3acbb27b0c7e1acb98d](https://i.gyazo.com/1c975a7ff55cb3acbb27b0c7e1acb98d.png)](https://gyazo.com/1c975a7ff55cb3acbb27b0c7e1acb98d)

I checked this site because that error message said that I should read.
https://developers.facebook.com/docs/facebook-login/permissions

In  this site, I cannot find  read_custom_friendlists permission.

What happened?

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
