### ISSUE TITLE
PHP 7.1 and mcrypt

### ISSUE THREAD

**Issue by standus** [facebook/php-graph-sdk#663]
Please prepare library for deprecated mcrypt in PHP 7.1
see https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by SammyK** [comment]
Thanks @standus but the Facebook PHP SDK does not use ext/mcrypt so we're good. :)

**Comment by applibs** [comment]
Ok, sorry, now I see that there is conditions for default string 
generator and if openssl exists it will us it, .
Thank you.

**Comment by holtkamp** [comment]
Just a pointer for other users trying to "not depend" on mcrypt. 

Just switched to PHP 7.1.0-RC5 and deprecation notices are being thrown when using the last stable version of the API: ```5.4```. This is caused due to [mcrypt functions being available and therefore be used (first preferred option)] (https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/PseudoRandomString/PseudoRandomStringGeneratorFactory.php#L79-L81)

This can be prevented by either:

- not installing the mcrypt extension, so no mcrypt function is available for use
- explicitly provide a ```pseudo_random_string_generator``` configuration option (for example ```openssl```) when initializing ```\Facebook\Facebook($config)```

It might be worth considering to change the order of preference and prefer ```openssl``` over ```mcrypt```, since ```mcrypt``` will be phased out...

**Comment by SammyK** [comment]
Thanks for the suggestion, @holtkamp! We should probably put a check in for `random_bytes()` first which will prevent the use of mcrypt on PHP >= 7. Would you mind creating a new issue for this or even submitting a PR for this? :)

**Comment by SammyK** [comment]
Actually, I'll post a quick PR in just a sec for this. :)

**Comment by holtkamp** [comment]
wow, nice suggestion indeed! 👍

**Comment by holtkamp** [comment]
@SammyK can you consider tagging a new (minor/patch) version for this?

**Comment by SammyK** [comment]
@holtkamp Yep! Just wanting on a review from a @yguedidi :)

**Comment by yguedidi** [comment]
@SammyK done! :)

**Comment by SammyK** [comment]
Thanks @yguedidi!

@holtkamp This is tagged in [5.4.2](https://github.com/facebook/php-graph-sdk/releases/tag/5.4.2). :)

**Comment by holtkamp** [comment]
Thanks @yguedidi and @SammyK, just updated to ```5.4.2```, works like a charm! No more need to

>explicitly provide a pseudo_random_string_generator configuration option (for example openssl) when initializing \Facebook\Facebook($config)
