### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by leeppolis** [facebook/php-graph-sdk#917]
I cannot understand how to issue an API call to get URL info with the PHP SDK.
The example code in the documentation available here: https://developers.facebook.com/docs/graph-api/reference/v2.11/url seems to be incomplete.

```
/* PHP SDK v5.0.0 */
/* make the API call */
try {
  // Returns a `Facebook\FacebookResponse` object
  $response = $fb->get(
    '/',
    '{access-token}'
  );
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}
$graphNode = $response->getGraphNode();
/* handle the result */
```

In this example, the `$url` variable is completely missing. I tried adding `?id=$link` to the endpoint, but it does not work. Is there a place where I can find more documentation and examples/ 

Thanks in advance.
S.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
