### ISSUE TITLE
Response Exception: An unknown error has occurred.

### ISSUE THREAD

**Issue by Simon1207** [facebook/php-graph-sdk#919]
When i'm log in with my fb-callback.php an unknown error has ocurred. i've tried with Graph api tool and it works but in the code i can't fix the error. my code is the next

`<?php 
	require_once "config.php";
	try{
		$accessToken=$helper->getAccessToken();
	}catch(\Facebook\Exceptions\FacebookResponseException $e){
		echo "Response Exception: " .$e->getMessage(); 
		exit();
	}catch(\Facebook\Exceptions\FacebookSDKException $e){
		echo "SDK Exception: " .$e->getMessage();
		exit();
	}

	if(!$accessToken){
		header('Location: login.php');
		exit();
	}
	$oAuth2Client=$FB->getOAuth2Client();
	if(!$accessToken->isLongLived())
		$accessToken=$oAuth2Client->getLongLivedAccessToken($accessToken);
	$response=$FB->get("/me?fields=id,first_name,last_name,email,picture.type(large)",$accessToken);
	$userData=$response->getGraphNode()->asArray();
	var_dump($userData);
 ?>`

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
