### ISSUE TITLE
Post on pages

### ISSUE THREAD

**Issue by butavpaul** [facebook/php-graph-sdk#921]
Hi. In my admin panel I'm using php sdk v2.5 for posting my content on my own pages! 'publish_pages' and 'manage_pages' are not approved because is for admins use only and until now it worked perfectly. I have more than 20 pages so I've used this method to post the content.
Without any response from the sdk, now is not working anymore. I've tried also to program or direct post on my pages but it doesn't work. I don't know where to start to find out the problem because I don't see any callback.
Thank you!

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
