### ISSUE TITLE
Facebook\Exceptions\FacebookAuthenticationException: (#324) Requires upload file in

### ISSUE THREAD

**Issue by ezekel** [facebook/php-graph-sdk#923]
I need some help please, why this error occurs "Facebook\Exceptions\FacebookAuthenticationException: (#324) Requires upload file in" when I upload photo , sometimes it works fine then when I upload again it shows that error again.

here is my code

```
 $data = [
                'message' => "Awesome test!",
                'source' => $fb->fileToUpload( $q->pathimage)
            ];
            try{

                $fb->post('/MyPage/photos', $data, $pagetoken);
             
            }catch(Facebook\Exceptions\FacebookResponseException $e) {
                Log::info( 'Graph returned an error: ' . $e->getMessage());

            } catch(Facebook\Exceptions\FacebookSDKException $e) {
                Log::info( 'Facebook SDK returned an error: ' . $e->getMessage());

            }
```

Thank you in advance.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
