### ISSUE TITLE
FacebookAuthenticationException: Error validating access token: Session has expired

### ISSUE THREAD

**Issue by ezekel** [facebook/php-graph-sdk#924]
I have my useraccesstoken that was generated in graph api explorer. and also I extend it that it will never expire.. so I tried to use the token to get pageaccesstoken. and it works, I have done this in postman,now when I used this in my server sometimes works fine after second attempt of requesting like uploading , now I get error session is expired. then I get back to postman with same procedure the postman return the page access token and it is not expire, but why is it in my server it will expire.

```
https://graph.facebook.com/v2.11/me/accounts?access_token=myusertokenthatstillworking
``

Thank you in advance.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
