### ISSUE TITLE
Automatic login

### ISSUE THREAD

**Issue by ezekel** [facebook/php-graph-sdk#925]
Hi is it possible that the user will not redirect to login to get the short live useraccesstoken?because in my website i have a form to be filled by the registerd users then when they submit the form it will also post to my facebook page. Is this possible?

Thank you in advance

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
