### ISSUE TITLE
Scrape links via PHP SDK vs Explorer

### ISSUE THREAD

**Issue by pardoxp** [facebook/php-graph-sdk#927]
I'd like to know the difference between using scrape via PHP sdk and Explorer, in my particular case using SDK PHP I have a function in a class basically with this little snippet of code
`try{
        $scrape = $this->getFacebook()->post('/',array (
            'scrape' => 'true',
            'id' => $link
        ),
            $accessToken
        );
       $data['link'] = $link;
       $post = $this->getFacebook()->post('/',$data, $accessToken);
       return $post;

    }
    catch(FacebookResponseException $e) {
        return $this->validateToken($e);
    } catch(FacebookSDKException $e) {
        return sprintf('Facebook SDK returned an error: ' . $e->getMessage());
    }
`
 
My question is, if I make some changes in my page($link) metas such as og:image, I have to run this code 2-4 times to see changes in the facebook post related to this link however I use [Facebook Explorer Tool directly](https://developers.facebook.com/tools/explorer), then I post and changes are corrected to the first attempt.. Any Ideas>?? Thanks in advance!!!!!!

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
