### ISSUE TITLE
Feed redirect without post_id

### ISSUE THREAD

**Issue by Xiscollado** [facebook/php-graph-sdk#935]
Despite i have publish_permissions granted, i don´t receive post_id from facebook when an user shares a feed. Any idea? It´s been working since two weeks ago without problems.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
