### ISSUE TITLE
Graph returned an error: Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.

### ISSUE THREAD

**Issue by pratika2395** [facebook/php-graph-sdk#937]
It worked fine till yesterday.. but today its not working.. Why this error has occured. I generated a new token with extended access token expiry(2 months).

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
