### ISSUE TITLE
Access Token should not be mandatory

### ISSUE THREAD

**Issue by sergentrif** [facebook/php-graph-sdk#938]
When I tried to request `GET /oauth/access_token` to obtain an App Token,  I received the FacebookSDKException `You must provide an access token.`. 

But the purpose of this route is to get an access token because we don't have one. I made it work by setting a fake Access Token with value `fake-token` but it's a little tricky.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
