### ISSUE TITLE
Can't load URL: The domain of this URL isn't included in the app's domains.

### ISSUE THREAD

**Issue by nchankov** [facebook/php-graph-sdk#939]
Got an issue, when I am trying to login with php sdk with Strict mode in OAuth section enabled.

The functionality working as expected when the strict mode is disabled, but if it's enabled, I got  exception `Facebook\Exceptions\FacebookResponseException` with the error:

*Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.*

Here is what I got:
facebook/graph-sdk ^5.5 (in composer) with php 5.6

example site: https://stage.domain.co.uk
fb login url: https://stage.domain.co.uk/fb

in the App->Settings->Basics in the "App Domains" field "stage.domain.co.uk" is present, as well as "domain.co.uk".

The domain stage.domain.co.uk is in the App->Settings->Advanced->Domain Manager section (not sure if this is relevant)

Also the app is managed through Business Manager and the domain is added in it as well

In the Facebook Login->Settings, under the "Valid OAuth redirect URIs" the values in the field contains

https://stage.domain.co.uk/fb is added as well as:
https://stage.domain.co.uk/fb/ (just in case)
http://stage.domain.co.uk/fb (http just in case)

So here is the pseudocode which I am using to create facebook redirect url

```
$callback = 'https://stage.domain.co.uk/fb';
$scope = [...];
$fb = new Facebook\Facebook([
....config data...
]);
$helper = $this->fb->getRedirectLoginHelper();
$loginUrl = $helper->getLoginUrl($callback, $scope);
header('Location: '.$loginUrl);
```

In addition:
I am pretty sure there is no typo in the app configuration like misspelled domain or wrong Valid OAuth url as they are quite short and I've checked and re-typed them couple of times already.

I've tried with JavaScript SDK and I've been able to get Access Token without a problem with this app

Please any help will be much appreciated.

**Comment by mdevine82** [comment]
So I'm not sure if this is root of the problem but Facebook doesn't like any parameters as part of the redirect URL when making the call for getAccessToken() after the initial callback.  I want to clarify that this isn't a fix, so feel free to try it but don't implement it into your application.

Here is the call in the library within: FacebookRedirectLoginHelper.php.  
```
public function getAccessToken($redirectUrl = null)
    {
        if (!$code = $this->getCode()) {
            return null;
        }

        $this->validateCsrf();
        $this->resetCsrf();

        $redirectUrl = $redirectUrl ?: $this->urlDetectionHandler->getCurrentUrl();
        // At minimum we need to remove the state param
        $redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state']);

        return $this->oAuth2Client->getAccessTokenFromCode($code, $redirectUrl);
    }
```

I noticed that after the second to last call to removeParamsFromUrl that my $redirectUrl still contained the '?code=abc123' parameter.  Just to test this out I added code to the removal and it seemed to work.  

```
$redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state']);

to 

$redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state', 'code']);
```
I'll post this on Facebook also because I'm not sure if the filtering is too strict (I assume it is) or if this is a bug in the URL parser.

**Comment by yguedidi** [comment]
@nchankov  just released the 5.6.2 version that fixes this issue! see #913, feel free to reopen this if your issue is not solved

**Comment by nchankov** [comment]
Thanks Yassine, indeed it fixed the issue. Any idea when this will be updated in the composer, so I could update it with it?

Thanks for both of you for identifying it and fixing it!

**Comment by yguedidi** [comment]
@nchankov it's on Packagist since some days! ;)

**Comment by aldos84** [comment]
I've the same problem too.
On my local dev system the login work very well but on live page I got the App Domain error.

The Redirect Urls are correctly and in every domain field I've added the correct domain of my live site.

Any idea why that login not work?

**Comment by bobmagicii** [comment]
same as aldos.

**Comment by NaitikShah** [comment]
Hey @aldos84 @bobmagicii did u get any solution??

**Comment by aldos84** [comment]
My problem was that my app runs in a VM and the FB helper got the wrong url (from the host system instead of main url)
My solution is to got the real url and set as parameter on $helper->getAccessToken()

```
$url = $this->url->getStatic($this->router->getRewriteUri()); // returns https://domain.com/facebook/login
$accessToken = $helper->getAccessToken($url);
```
in my fb development settings is the same url for valid redirect urls

**Comment by bobmagicii** [comment]
ah yes.

my problem was because i tried too hard to work like the cool kids do with local dev environments instead of the system i know works for me with dev instances in our cloud that i can properly https.

i was running the project locally with `php -S localhost:80 -t www` and using stunnel to chuck it down HTTPS because facebook wont even allow you to enter HTTP only urls anymore in the callback config. when doing this, PHP did not detect the HTTPS, so _SERVER['HTTPS'] never got sent, and facebook's url generator would constantly generate http urls for the redirect handlers instead.

**Comment by yguedidi** [comment]
@bobmagicii 

> by the time i found the offending code in the facebook library in how it generates its urls to send out, i was so pissed i even forgot i came here and just ragequit for the day.

It would be really helpful if you send a pull request to enhance it ;)
