### ISSUE TITLE
Facebook SDK returned an error:

### ISSUE THREAD

**Issue by mubasharbinafzal** [facebook/php-graph-sdk#945]
Cross-site request forgery validation failed. Required param "state" missing from persistent data.

**Comment by mubasharbinafzal** [comment]
on localhost this code is running but on server throw this error

**Comment by mubasharbinafzal** [comment]
Facebook SDK returned an error: Cross-site request forgery validation failed. Required param "state" missing from persistent data.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
