### ISSUE TITLE
getting error - "An unknown error has occurred." too frequently on graph api v2.6 . 

### ISSUE THREAD

**Issue by snghaprv** [facebook/php-graph-sdk#948]
We are getting {"error_message":"An unknown error has occurred.", "error_code":"1" } in the response.

**Comment by burnacid** [comment]
I'm having the same problem. It isn't consistent though.

On a Get request for `/289622754558083/feed?fields=id,properties,from,message,created_time,updated_time,link&limit=1000
`
{"error":{"code":1,"message":"An unknown error occurred","error_subcode":99}}

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by snghaprv** [comment]
I have filed this issue on facebook-issue-tracker. But they closed the [issue](https://developers.facebook.com/bugs/650400332017880) and asked me to file it  on this project here.

**Comment by yguedidi** [comment]
@snghaprv The error is return from the Graph API, so it's a problem from the Graph API side.
If the isue happened randomly, then the SDK code is OK, maybe it's an issue with Graph API server?
I can't help you more than that, sorry.
