### ISSUE TITLE
Post as Page (Group Administrator)

### ISSUE THREAD

**Issue by jfvoliveira** [facebook/php-graph-sdk#955]
Hello. A few days ago I could post (with a page token) to a private group associated to that page (and the page is the group's admin).
Now I can't.

The token's permissions are: publish_actions, user_managed_groups, manage_pages, pages_show_list, publish_pages, public_profile

The Page is the group's admin. Not I get the error

```
"error" => [
      "message" => "Permissions error"
      "type" => "OAuthException"
      "code" => 200
      "error_subcode" => 1376025
      "is_transient" => false
      "error_user_title" => "No Permission to Post"
      "error_user_msg" => "You do not have permission to post in this group."
      "fbtrace_id" => "A9PGBilwdSH"
]
```

What changed between a few days ago and now? Why can't I post as a page in the group?

Thanks

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
