### ISSUE TITLE
appsecret_proof required

### ISSUE THREAD

**Issue by flameblue59** [facebook/php-graph-sdk#956]
Hi, I have tried to enter my appsecert_proof but I still received this following error.

`Fatal error: Uncaught exception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Invalid appsecret_proof provided in the API argument' in /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:106 Stack trace: #0 /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(225): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array) #4 /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\Fac in /home/admin/stidac/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 106`

I have no idea about it, here is how do I implement my code to call the function

```
	$appsecret_proof= hash_hmac('sha256', $accessToken, $appSecret); 

	$fb = new Facebook(array(
		'app_id' => $appId,
		'app_secret' => $appSecret,
		'default_graph_version' => 'v2.12',
		'appsecret_proof' => $appsecret_proof
	));
```
I have checked the appId and appSecret, they work fine. This issue only happen whenever I log out my account. I really appreciate any help. Thank you.

**Comment by UOCecalero** [comment]
Same issue here...

**Comment by UOCecalero** [comment]
I solved the problem. The problem was that I took the wrong AccessToken from the Facebook API Graph Explorer.
You have to select first your app and then generate your App AccessToken to use it from your server.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
