### ISSUE TITLE
Access token was not returned from Graph

### ISSUE THREAD

**Issue by sahilk2579** [facebook/php-graph-sdk#960]
require_once __DIR__ . '/../student/f/autoload.php';

    $fb = new \Facebook\Facebook([
     'app_id' => 'app_id',
     'app_secret' => 'app_secret',
     'default_graph_version' => 'v2.9',
      ]);

	if(isset($_GET['state']))
	{$_SESSION['FBRLH_state']=$_GET['state'];}
	$permissions = ['email'];
	$helper = $fb->getRedirectLoginHelper();
	$accessToken = $helper->getAccessToken();

this is returning on server and localhost

Fatal error: Uncaught Facebook\Exceptions\FacebookSDKException: Access token was not returned from Graph. in C:\xampp\htdocs\coach2\student\f\Authentication\OAuth2Client.php:230 Stack trace: #0 C:\xampp\htdocs\coach2\student\f\Authentication\OAuth2Client.php(166): Facebook\Authentication\OAuth2Client->requestAnAccessToken(Array) #1 C:\xampp\htdocs\coach2\student\f\Helpers\FacebookRedirectLoginHelper.php(255): Facebook\Authentication\OAuth2Client->getAccessTokenFromCode('AQD3NhNnEVPxySb...', 'http://localhos...') #2 C:\xampp\htdocs\coach2\tutor\register.php(408): Facebook\Helpers\FacebookRedirectLoginHelper->getAccessToken() #3 {main} thrown in C:\xampp\htdocs\coach2\student\f\Authentication\OAuth2Client.php on line 230

**Comment by nickcartery** [comment]
Same issue!!!!

**Comment by sahilk2579** [comment]
@nickcartery  update PHP SDK to v5  it worked for me  , i had v4

Download it from  [here](https://github.com/facebook/php-graph-sdk)

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by anshuarya0712** [comment]
thank you @sahilk2579 . It works

**Comment by haisamhameed** [comment]
thank you @sahilk2579
