### ISSUE TITLE
Missing access token

### ISSUE THREAD

**Issue by codearthungary** [facebook/php-graph-sdk#961]
Hi guys, I use Facebook php sdk in my site for login and register and this has worked so far. Now after the auth procedure, the access token missing. 

        $access_token = $this->get_access_token();
        if($access_token && $this->get_expire_time() > (time() + 30) || $access_token && !$this->get_expire_time()){
            $this->fb->setDefaultAccessToken($access_token);
            return $access_token;
        }
        // If we did not have a stored access token or if it has expired, try get a new access token
        if(!$access_token){
            try{
                $access_token = $this->helper->getAccessToken();
            }catch (FacebookSDKException $e){
                $this->logError($e->getCode(), $e->getMessage());
                return null;
            }
            // If we got a session we need to exchange it for a long lived session.
            if(isset($access_token)){
                $access_token = $this->long_lived_token($access_token);
                $this->set_expire_time($access_token->getExpiresAt());
                $this->set_access_token($access_token);
                $this->fb->setDefaultAccessToken($access_token);
                return $access_token;
            }
        }

Maybe the FB changed something. OAuth redirect URIs set correct and tested.
Any idea?

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
