### ISSUE TITLE
Problem with Custom Aduience and PHONE numbers

### ISSUE THREAD

**Issue by egadirov** [facebook/php-graph-sdk#962]
Hi guys!
I have a problem when creating a custom audience with phone numbers.
On the Facebook Bossines page, the audience is created, the N of rows is added and the status "Audience is too small" does not change.
Before that, I sent emails and everything was successful.

Here is a piece of my code:

`	
      // In reality, I added an array of 1000 unique phones

 $phones = array( 
'+380999705715',
                            '+380999728338',
                             '+380999766495',
                             '+380999785178',
                              '+380999816697' );

$audience = new CustomAudience(null, $actAccount);

$audience->setData(array(
			CustomAudienceFields::NAME => $name,
			CustomAudienceFields::SUBTYPE => CustomAudienceSubtypes::CUSTOM,
			CustomAudienceFields::DESCRIPTION => $description,
));

$audience->create();

$audience->addUsers($phones, CustomAudienceTypes::PHONE);

`

**Comment by JaredClemence** [comment]
Are you 100% certain that the minimum required number of audience members in our 1000 phone numbers have:

* Associated the provided phone number with their facebook account
* Made that phone number public to allow it to be used for audience inclusion

The biggest problem I have with Facebook Custom Audiences is with the provided data not linking to a sufficient number of authorized accounts.  One way to verify that this is indeed a problem with this application and not with your data set is to use your 1000 phone numbers to create a custom audience using the Power Editor on Facebook.  If the audience fails there as well, then this issue can be closed out here, because it is not a problem with this library.

If the Power Editor produces a successful audience and this library still does not..., then we know that there is something that needs to be fixed.

What are your thoughts on the above? Have you tried anything new since you posted?

**Comment by egadirov** [comment]
Can't be 100%, but I take phone numbers from a file that manually feeds to facebook and gets success.
I do not think that the logic of feeding is different from the manual and using the API

**Comment by JaredClemence** [comment]
So, to be clear...

When you use these phone numbers and upload them to facebook manually, your audience is created successfully --- You don't have an issue with the audience being 'too small'.

When you create the audience with this package, the audience is 'too small'

Is that correct?

**Comment by yguedidi** [comment]
Hi! You sould post your question in https://github.com/facebook/facebook-php-business-sdk
