### ISSUE TITLE
OAuth redirect URL in another subdomain ? Cross-site request forgery validation failed. Required param "state" missing from persistent data.

### ISSUE THREAD

**Issue by PapaLimaZulu** [facebook/php-graph-sdk#964]
Since the "Use Strict Mode for Redirect URIs" became obligatory I have an issue with my application. It uses the
**user.myapp.com**
schema to allow different users to log inte their "work area". But while the list of the users is dynamic, I cannot modify the Client OAuth Settings every time a new user is added.
Is there any solution to this problem?
What I did was to create a dedicated app.myapp.com subdomain, added it to "Valid OAuth Redirect URIs" list and passed it URL to FB login.
But in this case I am getting:
**Cross-site request forgery validation failed. Required param "state" missing from persistent data.**
message (I call FB login from app1.myapp.com, the callback is at app.myapp.com with an intention to redirect back to app1.myapp.com)
Just to clarify: if, for test purposes, I redirect back to app1.myapp.com, everything works great. So the code is correct.

**Comment by RobbieLePommie** [comment]
This is not a bug, it's by design to totally prevent you doing exactly what you are doing (or rather to prevent someone else from doing it, in your name). But there's an easy work around.

The "state" is stored in the session handler. So there are two things you need to do:

1. If "app" and "app1" are on different servers or using different configs, you need to overwrite the session handler to save session details in a shared location. See http://php.net/manual/en/session.customhandler.php

2. As the sessionID is stored in a cookie, make sure that cookie is per domain (i.e. use ".domain.com" as the cookie domain). Otherwise you need a custom way of passing the sessionID to your callback handler. 

Works a charm once you do those.

**Comment by yguedidi** [comment]
Thanks @RobbieLePommie for this detailed answer!
