### ISSUE TITLE
/me/groups returns empty

### ISSUE THREAD

**Issue by vnikolay** [facebook/php-graph-sdk#967]
Before yesterday everything worked well, but now it gets an empty array:
$response = $fb->get('/me/groups', $access_token);
$data = $response->getGraphEdge()->asArray();
It doesn't work only for getting user managed groups. For '/me/accounts' it returns fan pages well.
I didn't do anything with code, it just stopped working, what is the problem?

**Comment by eugenecooper** [comment]
The same here. Most like it's because of the recent policy changes but it's not clear why other permissions left intact until August and group permissions simply disappeared from approved apps.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
