### ISSUE TITLE
test login sdk 5.6.2

### ISSUE THREAD

**Issue by wiixajax** [facebook/php-graph-sdk#971]
*test code*

```
function login(){
        $fb = new Facebook\Facebook([
            'app_id'                  => {my_app_id}, 
            'app_secret'              => {my_api_secret},
            'default_graph_version'   => 2.2
        ]);
        $helper = $fb->getRedirectLoginHelper();

        $permissions = ['email']; // Optional permissions
        $loginUrl = $helper->getLoginUrl($this->callback, $permissions);

        echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';
}
```

loginurl=
https://www.facebook.com/2.2/dialog/oauth?client_id=213113115860994&state=2fb2505649882585bed161cb34675b66&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=https%3A%2F%2Fdemo.168money.com.tw%2FTestLogin%2Ffbcallback&scope=email

page return content 
>>>

無法瀏覽此頁面
你點擊進來的連結可能已失效，或頁面可能已被移除。

why ?

**Comment by brianzaky** [comment]
[FBNotifications-master.zip](https://github.com/facebook/php-graph-sdk/files/1998057/FBNotifications-master.zip)

**Comment by brianzaky** [comment]
https://www.facebook.com/2.2/dialog/oauth?client_id=213113115860994&state=2fb2505649882585bed161cb34675b66&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=https%3A%2F%2Fdemo.168money.com.tw%2FTestLogin%2Ffbcallback&scope=email

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
