### ISSUE TITLE
Passing the state ?

### ISSUE THREAD

**Issue by michaelsomerville** [facebook/php-graph-sdk#972]
We figured out how to get rid of the url error, which everyone has been having issues with. But what I am currently lost with, is passing the state.

We need it to change all the time for our users - meaning that can't add a callback url specific to it. Where are we to add or edit the ability to change or pass the state with the PHP SDK to facebook?

Thanks!!

**Comment by csimpi** [comment]
Same question here.
Temporarily I'm adding the state parameter manually, and set the session's value.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by yguedidi** [comment]
@michaelsomerville @csimpi now that the formal answer is done, regarding your issue, I'd suggest you to simply use the session.
The `state` param is there to protect against CSRF attacks.
Just save in the session the user related data before redirecting to the login URL, using a fixed redirect URL (something like `https://myhost/fb-callback`) that is add in the app configuration as allowed redirect URL. Then if the user authenticate successfully, get the user related data from the session.

**Comment by csimpi** [comment]
I can't really accept the formal answer.
Our question is about Graph API PHP SDK, not Graph API itself only.
Still, If I'd pass custom params through the URI there should be a parameter of getLoginUrl() function that accepts the state parameter's value. 
Yes, state param is there to protect against CSRF attacks, I'd be comfortable to pass those parameters through the state param, not only store them in session since that's not secure.

**Comment by yguedidi** [comment]
I may misunderstood then...

If I understand correctly, you want to be able to pass a custom state containing user specific data instead of the random one generated to protect against CSRF, right?
If so, to me, it looks like a weird usage of the state param, and the `getLoginUrl()` function.
If I'm right understanding the usage, then it's a really specific one, and I think we won't support it and ease to use the SDK that way.
Especially when you could use your own `PersistentDataHandler` doing the logic you want.

> not only store them in session since that's not secure.

the state itself is stored in the session, why you think it's not secure?

PS: the formal answer has a section saying "For help about how to use the SDK, ...", and it looks like your issue fits in that case :wink:

**Comment by rajatmasih-web4realty** [comment]
Hey you can pass custom state param like this
`$helper = $fb->getRedirectLoginHelper();`
`$pdata = $helper->getPersistentDataHandler();`
`$pdata->set('state', "124545454");`
`$url= $helper->getLoginUrl($callback_url, $this->fb_permissions);`
