### ISSUE TITLE
Insecure Login Blocked

### ISSUE THREAD

**Issue by lokprakashpandey** [facebook/php-graph-sdk#975]
![capture](https://user-images.githubusercontent.com/8023202/38770290-b905663c-3fde-11e8-8148-e2e4712bc373.JPG)
When trying to use 'Log In with FB', it says, "Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://". How to deal with this problem?

**Comment by prappo** [comment]
Same problem. Did you get any solution yet?

**Comment by lokprakashpandey** [comment]
Yes...needs HTTPS

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by ashutosh925** [comment]
I am facing the same Problem, 
https://stackoverflow.com/questions/51726032/django-social-auth-facebook-valid-url-callback?noredirect=1#comment90412297_51726032

How did You solved the issue did you change  call back url in facebook app
