### ISSUE TITLE
Graph returned an error: Invalid appsecret_proof provided in the API argument

### ISSUE THREAD

**Issue by Ravindrage** [facebook/php-graph-sdk#986]
Hello , 
Today I created a new facebook App in  V2.12 and using this SDK. 
My previous created app is working fine with this SDK .script is posting image videos on my fb wall 
In new APP I am getting this error  . 
Graph returned an error: Invalid appsecret_proof provided in the API argument

I copy correct App Id and Secret and create a Correct Access token using 
https://developers.facebook.com/tools/explorer/

I  add a new App Product  like Facebook Login setup still not finished

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
