### ISSUE TITLE
Ads Actions Stats purchase and other values 

### ISSUE THREAD

**Issue by AbdurRehman26** [facebook/php-graph-sdk#987]
Hi i have been trying to fetch purchase and add to cart values using graph sdk but i cant seem to figure out the syntax to do it.. It would be helpful if anyone can provide the correct syntax to do it.  This is the link i am referring to 

https://developers.facebook.com/docs/marketing-api/reference/ads-action-stats/

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
