### ISSUE TITLE
UAn uncaught Exception was encountered

### ISSUE THREAD

**Issue by karthisgk** [facebook/php-graph-sdk#993]
Type: Error

Message: Class 'Facebook\Exceptions\FacebookSDKException' not found

Filename: /opt/lampp/htdocs/img_script/application/third_party/Facebook/Facebook.php

Line Number: 139

Backtrace:

File: /opt/lampp/htdocs/img_script/application/controllers/Profile.php
Line: 19
Function: __construct

File: /opt/lampp/htdocs/img_script/index.php
Line: 315
Function: require_once

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
