### ISSUE TITLE
FB Error

### ISSUE THREAD

**Issue by IsisEinaudi** [facebook/php-graph-sdk#994]
Hi, 
I cannot retrieve events information from https://graph.facebook.com/v2.10/isiseinaudi/events?fields=owner,start_time,cover,description,name,place&access_token=
It was correct untile few weeks ago, but now it does not work anymore.
Could you help me?
Best Regards
Isis Einaudi Dalmine

**Comment by allatvedelem** [comment]
Hello there 🙂
I trying to make an application for the orphan dogs in my country
But last night Facebook deleted my email 
Everything gone

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by allatvedelem** [comment]
Hello
I would like restore my fault. I lost soskutya2015@gmail.com account by Facebook. 
How can I ask back
