### ISSUE TITLE
Cross-site request forgery validation failed. Required param "state" missing from persistent data

### ISSUE THREAD

**Issue by arpitmca1992** [facebook/php-graph-sdk#995]
Trying to do simple thing below and getting above error:
In Index.php
`$helper = $fb->getRedirectLoginHelper();
$permissions = ['user_posts','publish_actions','manage_pages','publish_pages']; // Optional permissions
$loginUrl = $helper->getLoginUrl('http://test.org/Test/login-callback.php',$permissions);

echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';`

And In Callback.php

`$helper = $fb->getRedirectLoginHelper();
$accessToken = $helper->getAccessToken();
var_dump($accessToken);`

**Comment by cjluzius** [comment]
I noticed your using http. Should it be https? 

I'm having similar issues. I have one app that works with the Redirect Login fine but my older app that I'm converting from a Canvas Login keeps returning cross-site errors even though I've authorized the URLs and triple checked everything. When I test my URLs they all return that they are authorized so I have no idea on what to try next.

**Comment by arpitmca1992** [comment]
Dear you just start session in index file or redirect file your isshu will
be resolve. please tell me if it works. in my case it works.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by cjluzius** [comment]
arpitmca1992 I have start session as the first line of code. That's not the issue.
