### ISSUE TITLE
How to set up Facebook send dialog via PHP SDK?

### ISSUE THREAD

**Issue by chendejie** [facebook/php-graph-sdk#996]
I checked Facebook send dialog at here https://developers.facebook.com/docs/sharing/reference/send-dialog
All the sample are from JS SDK. Our web based on PHP, so, is there a way to do the Facebook send dialog via PHP SDK? Is there any Facebook doc for that?
Thank you!

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
