### ISSUE TITLE
Getting same error each time Unsupported get request. Object with ID 'xxxxxxx' does not exist, cannot be loaded due to missing permissions, or does not support this operation.

### ISSUE THREAD

**Issue by nileshsmartwebtech** [facebook/php-graph-sdk#999]
I am getting error when try to getting campaign
`Unsupported get request. Object with ID 'ad_account_id' does not exist, cannot be loaded due to missing permissions, or does not support this operation. Please read the Graph API documentation at https:\/\/developers.facebook.com\/docs\/graph-apiError Code: 100`

What was problem??

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
